name: Publish
on: 
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
    - name: Build
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"
    - run: git add -f _site
    - run: |
        git config --global user.email "cschleiden@outlook.com"
        git config --global user.name "Christopher Schleiden" 
    - run: git commit -m "${{ github.sha }}"
    - run: git push -f origin master:site